### ISSUE TITLE
Ability to detect virtual Amiga drive inside MBR 0x76 partition

### ISSUE THREAD

**Issue by drovnotya** [henrikstengaard/hst-imager#10]
SD cards partitioned for use with the pistorm accelerator boards have a partition with ID 0x76 that are recognized by the Amiga as a disk.

The process for manually partitioning a drive in this manner is described here:

https://github.com/michalsc/Emu68/blob/master/docs/tutorials/SD_Preparation.md

HST-Imager can be used to create a RDB based disk image, which then can be made pistorm usable by running it through this tool:

https://github.com/PiStorm/hdf2emu68

However, in the resulting image file the RDB disk is now "hidden" inside the 0x76 partition and HST-Imager no longer recognizes it.

It would be nice if HST-Imager could recognize the "disk/partitions inside the partition", so that the process of maintaning a pistorm compatible image could be done with one (less) tool.

This way of having a virtual Amiga drive within a DOS partition seems to have been established with Amithlon, and is also recognized by WinUAE.

**Comment by henrikstengaard** [comment]
I haven't used pistorm accelerator yet, but have a pistorm32 lite to test with.

Having an entire RDB disk put inside a MBR partition is not a use case I have considered, which is why Hst Imager currently doesn't support it.

I'm not sure how to support this in the gui as 1 disk then actually contain multiple disks then there should be an additional dropdown with selection of entire disk or "sub-disk" detected within a partition. Maybe it would be better to support reading and writing single partitions instead in gui. I need to consider this.

For console it also somehow needs to display information about the entire disk as it does now with support of detecting additional disks in partitions and list those as well. A console path to an RDB disk inside a MBR partition could be something like "pistorm.img/mbr/1/rdb/dh0".

Is it primarily the console you're using and requesting to support this?

**Comment by dcutugno** [comment]
Would be great, any progress on this? if you need testers let me know...

**Comment by henrikstengaard** [comment]
Yes, newly released Hst Imager v1.2.390 has full support for PiStorm partitions of type 0x76 including file system, dir, copy and extract commands as well with all RDB commands.
